title: "Demo site"
lang: "bg"
description: "Испанска граматика и лексика чрез проста практика."

owner: "Anna Ilieva"
email: "your.email.here@gmail.com"
baseurl: "" # the subpath of the site
url: "https://tu-paso-a-paso.github.io"

# type --> "pages", "posts", "drafts" or any custom created collection
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/posts/:title"
      excerpt_separator: <!--more-->
  - scope:
      path: ""
    values:
      toc: true
      aside: true

# table of contents
toc:
  min_level: 1
  max_level: 3
  list_class: toc-list
  sublist_class: toc-sublist

plugins:
  - jekyll-toc
